services:
  - type: web
    plan: free
    runtime: image
    name: n8n-iconicskills1
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_PORT
        value: "5678"
      
      - key: PORT
        value: "5678"

      - key: N8N_HOST
        value: "0.0.0.0"

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      # Parse from your Neon connection string
      - key: DB_POSTGRESDB_HOST
        value:ep-solitary-base-b4q36a3r-pooler.c-6.us-east-2.aws.neon.tech  # YOUR HOST
        
      - key: DB_POSTGRESDB_PORT
        value: "5432"
        
      - key: DB_POSTGRESDB_DATABASE
        value: neondb  # YOUR DATABASE NAME
        
      - key: DB_POSTGRESDB_USER
        value: neondb_owner  # YOUR USERNAME
        
      - key: DB_POSTGRESDB_PASSWORD
        sync: false  # Set in Render dashboard: YOUR PASSWORD

      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"

      - key: N8N_WEBHOOK_URL
        value: https://n8n-iconicskills1.onrender.com/
